version: '3'
services:
   web:
    build: .
    ports:
       - "5000:80"
    volumes:
        - .:/app
    depends_on:
        - db
        - redis
    env_file:
        - ./.env        

   db:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=47VD78TCfOlrQ3CWKWERAajL2Qdawzi5
          - POSTGRES_DB=my_database_0du9
      volumes:
          - postgres_data:/var/lib/postgressql/data
      ports:
      - "5432:5432"  
   redis:
    image: redis
    ports:
      - "6379:6379"    

volumes:
    postgres_data:                